name: coach_app
description: A Flutter app for freelance coaching with booking, packages, and client tracking
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  rxdart: ^0.27.7

  # Supabase for backend
  supabase_flutter: ^2.3.2
  
  # Google Sign In & Calendar API
  google_sign_in: ^6.2.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1

  # Firebase removed - using Supabase only
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.16.0
  # cloud_firestore: ^4.14.0

  # UI Components
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.9
  intl: ^0.20.2
  fl_chart: ^0.65.0
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  liquid_pull_to_refresh: ^3.0.1
  badges: ^3.1.2
  
  # Animations
  lottie: ^3.0.0
  animations: ^2.0.11
  
  # Real-time Features
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2

  # Payment
  flutter_stripe: ^10.1.1
  qr_flutter: ^4.1.0

  # PDF Generation for Invoices
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1

  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Permissions
  permission_handler: ^11.2.0

  # HTTP requests
  http: ^1.1.2
  dio: ^5.4.0

  # UUID for generating IDs
  uuid: ^4.2.2
  
  # Image handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  file_picker: ^6.1.1
  
  # Other utilities
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.3
  
  # Device Preview for iPhone/Android virtual frames
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Add custom fonts if needed
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
